update_etf:
  name: "Purchase ETF"
  fields:
    entity_id:
      name: "Select ETF to Purchase"
      description: "Select one of the ETF entities to purchase more of."
      required: True
      selector:
        entity:
          filter:
            domain: sensor
            integration: etf_monitor
          multiple: False
    amount:
      name: "Amount of New Shares"
      description: "Select how many ETFs you would like to buy."
      required: True
      example: 10
      default: 0
      selector:
        number:
          min: 0
    price:
      name: "Price per Share"
      description: "Give in the price per ETF in euros"
      required: True
      example: 55.6
      default: 0.0
      selector:
        number:
          min: 0.0
          step: 0.01
          unit_of_measurement: "Euro"
    date:
      name: "Purchase Date"
      description: "Give the date of purchase."
      required: False
      example: "2024-02-22"
      selector:
        date:
